# config/packages_mapping.yaml
packages:
  vim: "$HOME/.vim"
  zsh: "$HOME"
  emacs: "$HOME/.emacs.d"
  kitty: "$HOME/.config/kitty"
  bspwm: "$HOME/.config/bspwm"
  fontconfig: "$HOME/.config/fontconfig"
